version: '3.8'

services:
  stockflow-api:
    image: stockflow-api
    container_name: stockflow-api
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stockflow-db:5432/stockflowApi
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://stockflow-db:5432/stockflowApi
      - SPRING_THREADS_VIRTUAL_ENABLED=true
    ports:
      - '8081:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      stockflow-db:
        condition: service_healthy
    restart: unless-stopped

  stockflow-db:
    image: postgres:17.4
    container_name: stockflow-db
    environment:
      - POSTGRES_USER=stockflowApi
      - POSTGRES_DB=stockflowApi
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U stockflowApi -d stockflowApi']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - stockflow_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  stockflow_postgres_data:
    driver: local
