# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: stockflow-api
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # SMTP server
      - 8025:8025 # Web UI

  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
