package com.adeem.stockflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CartAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartAllPropertiesEquals(Cart expected, Cart actual) {
        assertCartAutoGeneratedPropertiesEquals(expected, actual);
        assertCartAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartAllUpdatablePropertiesEquals(Cart expected, Cart actual) {
        assertCartUpdatableFieldsEquals(expected, actual);
        assertCartUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartAutoGeneratedPropertiesEquals(Cart expected, Cart actual) {
        assertThat(actual)
            .as("Verify Cart auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartUpdatableFieldsEquals(Cart expected, Cart actual) {
        assertThat(actual)
            .as("Verify Cart relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartUpdatableRelationshipsEquals(Cart expected, Cart actual) {
        assertThat(actual)
            .as("Verify Cart relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
