package com.adeem.stockflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductFamilyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductFamilyAllPropertiesEquals(ProductFamily expected, ProductFamily actual) {
        assertProductFamilyAutoGeneratedPropertiesEquals(expected, actual);
        assertProductFamilyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductFamilyAllUpdatablePropertiesEquals(ProductFamily expected, ProductFamily actual) {
        assertProductFamilyUpdatableFieldsEquals(expected, actual);
        assertProductFamilyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductFamilyAutoGeneratedPropertiesEquals(ProductFamily expected, ProductFamily actual) {
        assertThat(actual)
            .as("Verify ProductFamily auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductFamilyUpdatableFieldsEquals(ProductFamily expected, ProductFamily actual) {
        assertThat(actual)
            .as("Verify ProductFamily relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductFamilyUpdatableRelationshipsEquals(ProductFamily expected, ProductFamily actual) {
        // empty method
    }
}
