package com.adeem.stockflow.domain;

import static com.adeem.stockflow.domain.AssertUtils.bigDecimalCompareTo;
import static com.adeem.stockflow.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PurchaseOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseOrderAllPropertiesEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertPurchaseOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchaseOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseOrderAllUpdatablePropertiesEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertPurchaseOrderUpdatableFieldsEquals(expected, actual);
        assertPurchaseOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseOrderAutoGeneratedPropertiesEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertThat(actual)
            .as("Verify PurchaseOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseOrderUpdatableFieldsEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertThat(actual)
            .as("Verify PurchaseOrder relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getDate())
            )
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getShipping()).as("check shipping").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getShipping())
            )
            .satisfies(a ->
                assertThat(a.getMissionFee())
                    .as("check missionFee")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMissionFee())
            )
            .satisfies(a ->
                assertThat(a.getHandling()).as("check handling").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getHandling())
            )
            .satisfies(a ->
                assertThat(a.getCostTotal()).as("check costTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCostTotal())
            )
            .satisfies(a ->
                assertThat(a.getTvaRate()).as("check tvaRate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTvaRate())
            )
            .satisfies(a ->
                assertThat(a.getStampRate()).as("check stampRate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getStampRate())
            )
            .satisfies(a ->
                assertThat(a.getDiscountRate())
                    .as("check discountRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountRate())
            )
            .satisfies(a ->
                assertThat(a.getTvaAmount()).as("check tvaAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTvaAmount())
            )
            .satisfies(a ->
                assertThat(a.getStampAmount())
                    .as("check stampAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getStampAmount())
            )
            .satisfies(a ->
                assertThat(a.getDiscountAmount())
                    .as("check discountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountAmount())
            )
            .satisfies(a ->
                assertThat(a.getSubTotal()).as("check subTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubTotal())
            )
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseOrderUpdatableRelationshipsEquals(PurchaseOrder expected, PurchaseOrder actual) {
        assertThat(actual)
            .as("Verify PurchaseOrder relationships")
            .satisfies(a -> assertThat(a.getClientAccount()).as("check clientAccount").isEqualTo(expected.getClientAccount()))
            .satisfies(a -> assertThat(a.getAdmin()).as("check admin").isEqualTo(expected.getAdmin()))
            .satisfies(a -> assertThat(a.getSupplier()).as("check supplier").isEqualTo(expected.getSupplier()));
    }
}
