package com.adeem.stockflow.domain;

import static com.adeem.stockflow.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class QuotaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaAllPropertiesEquals(Quota expected, Quota actual) {
        assertQuotaAutoGeneratedPropertiesEquals(expected, actual);
        assertQuotaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaAllUpdatablePropertiesEquals(Quota expected, Quota actual) {
        assertQuotaUpdatableFieldsEquals(expected, actual);
        assertQuotaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaAutoGeneratedPropertiesEquals(Quota expected, Quota actual) {
        assertThat(actual)
            .as("Verify Quota auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaUpdatableFieldsEquals(Quota expected, Quota actual) {
        assertThat(actual)
            .as("Verify Quota relevant properties")
            .satisfies(a -> assertThat(a.getUsers()).as("check users").isEqualTo(expected.getUsers()))
            .satisfies(a -> assertThat(a.getProducts()).as("check products").isEqualTo(expected.getProducts()))
            .satisfies(a -> assertThat(a.getProductFamilies()).as("check productFamilies").isEqualTo(expected.getProductFamilies()))
            .satisfies(a -> assertThat(a.getShowcasedProducts()).as("check showcasedProducts").isEqualTo(expected.getShowcasedProducts()))
            .satisfies(a -> assertThat(a.getSaleOrders()).as("check saleOrders").isEqualTo(expected.getSaleOrders()))
            .satisfies(a -> assertThat(a.getPurchaseOrders()).as("check purchaseOrders").isEqualTo(expected.getPurchaseOrders()))
            .satisfies(a -> assertThat(a.getCustomers()).as("check customers").isEqualTo(expected.getCustomers()))
            .satisfies(a -> assertThat(a.getSuppliers()).as("check suppliers").isEqualTo(expected.getSuppliers()))
            .satisfies(a -> assertThat(a.getShipments()).as("check shipments").isEqualTo(expected.getShipments()))
            .satisfies(a ->
                assertThat(a.getResetDate())
                    .as("check resetDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getResetDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaUpdatableRelationshipsEquals(Quota expected, Quota actual) {
        // empty method
    }
}
