name: Deploy to VPS

on:
  push:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/stockflow-api
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build application
        run: |
          chmod +x ./mvnw
          ./mvnw clean compile -Pprod -DskipTests

      - name: Build and Push Docker image to Docker Hub
        run: |
          ./mvnw jib:build -Pprod -DskipTests \
            -Djib.to.image=${{ env.DOCKER_IMAGE }} \
            -Djib.to.tags=${{ env.DOCKER_TAG }},latest

      - name: Copy Docker Compose file to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: 'docker-compose.yml'
          target: /root/stockflow/
          strip_components: 0

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "Starting deployment..."

            # Create app directory and navigate
            mkdir -p /root/stockflow
            cd /root/stockflow

            IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/stockflow-api:${{ github.sha }}"

            # Login to Docker Hub on VPS
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            # Stop existing services gracefully
            echo "Stopping existing services..."
            docker-compose down 2>/dev/null || true

            # Update docker-compose.yml to use the Docker Hub image
            sed -i "s|image: stockflow-api|image: $IMAGE|g" docker-compose.yml

            # Pull the latest application image from Docker Hub
            echo "Pulling latest application image from Docker Hub..."
            docker pull $IMAGE

            # Start all services (app + database)
            echo "Starting application and database..."
            docker-compose up -d

            # Wait for services to fully start
            echo "Waiting for services to start..."
            sleep 40

            # Display service status
            echo "Checking service status..."
            docker-compose ps

            # Check application health
            echo "Checking application health..."
            sleep 10
            curl -f http://localhost:8081/management/health || echo "Health check failed - app may still be starting"

            # Show container logs if health check fails
            if ! curl -s http://localhost:8081/management/health > /dev/null; then
              echo "Showing application logs..."
              docker-compose logs stockflow-api --tail=20
            fi

            # Cleanup old unused images to save disk space
            echo "Cleaning up old images..."
            docker image prune -f

            # Logout from Docker Hub for security
            docker logout

            # Get public IP and show access URL
            PUBLIC_IP=$(curl -s ifconfig.me)
            echo "=================================="
            echo "Deployment completed successfully!"
            echo "Application URL: http://$PUBLIC_IP:8081"
            echo "Health Check: http://$PUBLIC_IP:8081/management/health"
            echo "PostgreSQL: $PUBLIC_IP:5433"
            echo ""
            echo "Container Status:"
            docker-compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"
            echo ""
            echo "Service Ports:"
            echo "- StockFlow API: 8081"
            echo "- StockFlow DB:  5433"
            echo "- IMS App:       8080 (existing)"
            echo "- IMS DB:        5432 (existing)"
            echo "=================================="
